#ifndef VOXEL_NAV_VIEWER_H
#define VOXEL_NAV_VIEWER_H

#ifdef VOXEL_ENABLE_NAVIGATION

#include "../../engine/ids.h"
#include "../../util/godot/classes/node_3d.h"

namespace zylann::voxel {

// Controls where navmesh is generated by proximity.
// Uses the same global registry pattern as VoxelViewer.
class VoxelNavViewer : public Node3D {
	GDCLASS(VoxelNavViewer, Node3D)
public:
	VoxelNavViewer();

	void set_nav_distance(unsigned int distance);
	unsigned int get_nav_distance() const;

	void set_enabled_in_editor(bool enable);
	bool is_enabled_in_editor() const;

protected:
	void _notification(int p_what);

private:
	static void _bind_methods();

	void sync_all_parameters();
	static void unregister_deferred_callback(const int64_t viewer_node_id, const Vector2i encoded_viewer_id);

	bool is_active() const;

	NavViewerID _viewer_id;
	unsigned int _nav_distance = 64;
	bool _enabled_in_editor = false;
	bool _pending_deferred_unregistration = false;
};

} // namespace zylann::voxel

#endif // VOXEL_ENABLE_NAVIGATION

#endif // VOXEL_NAV_VIEWER_H
